# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/dry-core/all/dry-core.rbi
#
# dry-core-0.4.8
module Dry
end
module Dry::Core
end
module Dry::Core::Constants
  def self.included(base); end
end
