# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ActiveSupport::TimeWithZone::TZInfo::TimezonePeriod; end
module Catalyst::RSpec; end
module T::Private::Methods::MethodHooks; end
module T::Private::Methods::SingletonMethodHooks; end
module Time::TZInfo::Timezone; end
